"""FastAPI entry point for document processing and grounded RAG services."""

import asyncio
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes.admin import router as admin_router
from app.api.routes.artifacts import router as artifacts_router
from app.api.routes.chunks import router as chunks_router
from app.api.routes.documents import router as documents_router
from app.api.routes.evaluation import router as evaluation_router
from app.api.routes.health import router as health_router
from app.api.routes.processing import router as processing_router
from app.api.routes.rag import router as rag_router
from app.core.config import get_settings
from app.core.logging import configure_logging
from app.api.error_handling import install_error_handling
from app.db.session import check_database_connection, engine
from app.services.chroma_service import get_chroma_service
from app.services.processing_worker import (
    get_processing_worker,
    recover_stale_processing_runs,
)
from app.services.evaluation_service import recover_stale_evaluations


settings = get_settings()
configure_logging(settings.log_level)


def _validate_managed_directory(path: Path) -> None:
    resolved = path.resolve()
    project_root = Path.cwd().resolve()
    forbidden = {Path(resolved.anchor), Path.home().resolve(), project_root}
    if resolved in forbidden:
        raise RuntimeError("A project-managed data directory is configured too broadly")
    resolved.mkdir(parents=True, exist_ok=True)
    if not resolved.is_dir():
        raise RuntimeError("A project-managed data path is not a directory")


@asynccontextmanager
async def lifespan(_app: FastAPI):
    """Validate local dependencies, recover stale work, and own one worker."""

    configure_logging(settings.log_level)
    _validate_managed_directory(settings.upload_root)
    _validate_managed_directory(settings.artifact_root)
    check_database_connection()
    get_chroma_service(settings).heartbeat()
    recover_stale_processing_runs(settings)
    recover_stale_evaluations(settings)
    worker = get_processing_worker(settings)
    if settings.processing_worker_enabled:
        worker.start()
    try:
        yield
    finally:
        await asyncio.to_thread(worker.stop)
        engine.dispose()


app = FastAPI(
    title=settings.app_name,
    version="0.12.0",
    description=(
        "Conventional RAG demonstration comparing PyMuPDF fixed chunks with local Docling "
        "structure-aware parsing. Docling conversion is local; original PDFs, page images, "
        "table images, and picture crops are never sent to Azure. When indexing is requested, "
        "only contextualized textual chunks are sent to the configured Azure text-embedding-3-large "
        "deployment. RAG sends only the question and retrieved textual evidence to the company "
        "GPT-5.1 deployment. Page numbers and bounding boxes are resolved from application "
        "provenance, never generated by the chat model. The controlled evaluation runs the fixed "
        "Project Aurora ground truth against both indexed representations with deterministic "
        "retrieval, answer, citation, abstention, latency, and token metrics. Granite-Docling "
        "remains an optional deferred extension."
    ),
    lifespan=lifespan,
    openapi_tags=[
        {"name": "Health", "description": "Safe local dependency health."},
        {"name": "Configuration", "description": "Redacted runtime readiness."},
        {"name": "Documents", "description": "Validated PDF upload and lookup."},
        {"name": "Processing", "description": "PostgreSQL-queued one-worker processing."},
        {"name": "Artifacts", "description": "Safe artifact metadata and streaming."},
        {"name": "Chunks", "description": "Chunk inspection and provenance overlays."},
        {"name": "RAG", "description": "Grounded retrieval and structured answering."},
        {
            "name": "Evaluation",
            "description": (
                "One-pass controlled Baseline/Docling evaluation with live Azure model calls, "
                "polling, deterministic metrics, idempotent reuse, and CSV/JSON exports."
            ),
        },
        {"name": "Demo Administration", "description": "Disabled-by-default scoped reset."},
    ],
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Accept", "Content-Type", "X-Request-ID"],
    expose_headers=["X-Request-ID", "Content-Disposition"],
)
install_error_handling(app)
app.include_router(health_router)
app.include_router(documents_router)
app.include_router(processing_router)
app.include_router(artifacts_router)
app.include_router(chunks_router)
app.include_router(rag_router)
app.include_router(evaluation_router)
app.include_router(admin_router)
